---
title: "R for Medical Research: modeling"
author: "Matt Broerman"
format: 
  html:
    embed-resources: true
---

```{r message=FALSE}
library(ggplot2)
library(readr)
library(dplyr)
library(lubridate)
library(broom)
library(gtsummary)

pe <- read_csv("data/procedureevents.csv")
adm <- read_csv("data/admissions.csv")
pt <- read_csv("data/patients.csv")
```


```{r}

adm |> 
  count(admission_type, sort = TRUE)

pe |> 
  count(ordercategoryname, sort = TRUE)

proc_from_adm <-
  adm |>
  left_join(pe) |>
  select(subject_id,
         hadm_id,
         admittime,
         starttime,
         admission_type, # new
         ordercategoryname) |>
  mutate(days_from_adm = (starttime - admittime) / ddays(1))

mod_data <- 
  pt |> 
  select(subject_id, gender, anchor_age) |> 
  left_join(proc_from_adm) |> 
  mutate(ER = admission_type == "EW EMER.") |> 
  filter(ordercategoryname == "Peripheral Lines") |> 
  select(subject_id, hadm_id, admittime, gender, anchor_age, ER, days_from_adm) |> 
  mutate(proc_12hr = max(days_from_adm < 0.5), .by = hadm_id) |> 
  mutate(tt_first_proc = min(days_from_adm), .by = hadm_id) |> 
  select(-days_from_adm) |> 
  distinct()

mod_data

```



```{r}
mod1 <- 
  mod_data |> 
  glm(proc_12hr ~ ER + gender + anchor_age, data = _, family = "binomial")
  
mod1 |> 
summary()


tbl_regression(mod1, exponentiate = TRUE)

```

